is2_014/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


# configuramos las rutas y vistas
from userstory.views import ver_archivo

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    #path('index/', TemplateView.as_view(template_name="index.html")),
    #path('index/', TemplateView.as_view(template_name="index.html"), name="index"),
    path('accounts/', include('allauth.urls')),
    path('index/logout', LogoutView.as_view()),
    url(r'^roles/', include('rol.urls')),
    path('logout', LogoutView.as_view()),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^proyectos/', include('proyecto.urls')),
    url(r'^usuarios/', include('usuarios.urls')),
    url(r'^clientes/',include('clientes.urls')),
    path(route='media/<int:archivo_id>/', view=ver_archivo, name='ver_archivo')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/urls.py
from django.conf.urls import include, url
from django.urls import path
# from proyecto import views
from . import views
from proyecto.views import eliminar2
from userstory.views import *
# from .views import eliminar2
#from tipoUserStory.views import *
#from userstory.views import *
from sprint.views import *

"""
Definicion de URLs contenidas en proyectos
"""

urlpatterns = [

    #administracion

    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^create/$', views.CreateProjectView.as_view(), name='create_project'),
    path(route='update_project/<int:pk_proyecto>/', view=views.UpdateProjectView.as_view(), name='update_project'),
    path("eliminar/<int:project_id>/", eliminar2, name="eliminar2"),
    #definicion

    url(r'^opciones/$', views.OptionsListView.as_view(), name='options_project'),
    path(route='opciones/<int:pk_proyecto>/', view=views.UpdateOptionsView.as_view(), name='update_options'),
    path('opciones/<int:pk_proyecto>/flujos/', include('flujo.urls')),
    path('opciones/<int:pk_proyecto>/tipoUserStory/', include('tipoUserStory.urls'), name='user_story_type_list'),
    path(route='opciones/<int:pk_proyecto>/asignarRoles/', view=views.UpdateTeamMemberView.as_view(), name='update_roles_proyecto'),

    #ejecucion

    url(r'^ejecuciones/$', views.EjecucionListView.as_view(), name='options_project'),
    path(route='ejecuciones/<int:pk_proyecto>/', view=views.UpdateEjecucionView.as_view(), name='update_ejecucion'),
    path('ejecuciones/<int:pk_proyecto>/userstory/', include('userstory.urls')),
    path(route='ejecuciones/<int:pk_proyecto>/productbacklog/', view=ProductBacklogListView.as_view(), name='product_backlog'),
    path('ejecuciones/<int:pk_proyecto>/sprint/', include('sprint.urls')),
    path(route='ver/<int:pk>/', view=views.VerProyectoDetailView.as_view(), name='ver_project'),
    path(route='ejecuciones/<int:pk_proyecto>/productbacklogpdf/', view=ProductBacklogPDF.as_view(), name="reporte_pb"),
    path(route='ejecuciones/<int:pk_proyecto>/horastrabajadas/', view=views.HorasTrabajadasPDF.as_view(),name="horas_trabajadas")
]

rol/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import eliminar3
# from django.contrib.auth.views import login
from .models import *

"""
URLs para el ver, crear y modificar roles
"""

urlpatterns = [
	url(r'^$', views.RolListView.as_view(), name='rol_list'),
	url(r'^create/$', views.CreateRolView.as_view(), name='create_rol'),
	path(route='<int:pk>/', view=views.UpdateRolView.as_view(), name='update_rol'),
	path(route='ver/<int:pk>/', view=views.VerRolDetailView.as_view(), name='ver_rol'),
	path("eliminar/<int:rol_id>/", eliminar3, name="eliminar3"),
]

sprint/models.py
from django.db import models
from django.core.exceptions import ValidationError
from proyecto.models import Proyecto
from django.utils import timezone
from datetime import timedelta
from userstory.models import UserStory, Actividad, HistorialEstimaciones

"""
Estados posibles del sprint
"""
ESTADOS_SPRINT = (
    ('Pendiente', 'Pendiente'),
    ('En Proceso', 'En Proceso'),
    ('Terminado', 'Terminado')
)

class Sprint(models.Model):
    """
    Modelo de la clase sprint, el cual representa un periodo de tiempo  definido dentro del
    proyecto al que se encuentra relacionado en el que se trabajan una cantidad definida de
    user stories
    """
    nombre = models.CharField(max_length=20, blank=False, null=False)
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)
    proyecto = models.ForeignKey('proyecto.Proyecto',on_delete=models.CASCADE, null=True)
    estado = models.CharField(max_length=25, choices=ESTADOS_SPRINT, default='Pendiente')
    dias_laborales = models.IntegerField(null=False)
    dias_habiles = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        """
        retorna el nombre del sprint
        """
        return self.nombre

    def has_dias_habiles(self):
        """
        retorna falso si no se ha definido ningun dia habil en el sprint o verdadero en
        caso de que exista por lo menos un dia habil durante el sprint
        """
        if not self.dias_habiles:
            return False
        return True

    def get_dias_habiles(self):
        """
        retorna la lista de dias habiles definidos para el sprint, siendo
        1: Lunes
        2: Martes
        3: Miercoles
        4: Jueves
        5: Viernes
        6: Sábado
        7: Domingo
        """
        dias_habiles = []
        dh = self.dias_habiles
        if dh:
            for d in dh.split(','):
                dias_habiles.append(int(d))
        return dias_habiles

    def get_nombres_dias_habiles(self):
        """
        retorna la lista nombres de dias habiles definidos para el sprint
        1: Lunes
        2: Martes
        3: Miercoles
        4: Jueves
        5: Viernes
        6: Sábado
        7: Domingo
        """
        dias_habiles = []
        dh = self.dias_habiles
        if dh:
            for d in dh.split(','):
                if d == '1':
                    dias_habiles.append('Lunes')
                elif d == '2':
                    dias_habiles.append('Martes')
                elif d == '3':
                    dias_habiles.append('Miércoles')
                elif d == '4':
                    dias_habiles.append('Jueves')
                elif d == '5':
                    dias_habiles.append('Viernes')
                elif d == '6':
                    dias_habiles.append('Sábado')
                elif d == '7':
                    dias_habiles.append('Domingo')
        return dias_habiles

    def validate(self):
        """
        Metodo del modelo de Sprint que lanza excepciones de tipo ValidationError en caso de
        que no se hayan completado todos los campos obligatorios en el sprint (dias hábiles,
        nombre y días laborales) en caso contrario retorna verdadero
        """
        if not self.has_dias_habiles():
            raise ValidationError('Debe ingresar al menos un dia hábil')
        if not self.nombre:
            raise ValidationError('Debe ingresar el nombre del sprint')
        if not self.dias_laborales or self.dias_laborales == 0:
            raise ValidationError('Debe ingresar al menos un dia laboral')
        if not self.proyecto:
            raise ValidationError('En sprint debe estar relacionado a un proyecto')
        return True

    def validate_test(self):
        """
        Metodo del modelo de Sprint que retorna un booleano en caso
        que no se hayan completado todos los campos obligatorios en el sprint.
        """
        if not self.has_dias_habiles():
            return False
        if not self.nombre:
            return False
        if not self.dias_laborales or self.dias_laborales == 0:
            return False
        if not self.proyecto:
            return False
        return True

    def get_duracion_real(self):
        """
        metodo del modelo Sprint que retorna la cantidad de dias de duracion del sprint en
        días hábiles
        :return:
        :dias: la cantidad de dias entre la fecha de inicio del sprint y la fecha de finalizacion
        del sprint, en caso de no tener fecha de finalizacion aun, hasta la fecha de hoy
        """
        if not self.fecha_inicio: return 0
        dias_habiles = self.get_dias_habiles()
        inicio = self.fecha_inicio
        if self.fecha_fin:
            fin = self.fecha_fin
        else:
            fin = timezone.now().date()
        currentdate = inicio
        dias = 0
        while currentdate <= fin:
            if currentdate.isoweekday() in dias_habiles:
                dias += 1
            currentdate += timedelta(days=1)
        return dias

    def get_user_stories(self):
        """
        metodo del modelo Sprint que retorna todos los user stories asignados al sprint
        :return: Todos los user stories del sprint
        """
        return UserStory.objects.filter(sprint=self.pk)

    def get_horas_trabajadas(self):
        """
        metodo de la clase Sprint que retorna el total de horas trabajadas en el sprint
        :return: total de horas trabajadas en el sprint
        """
        actividades = Actividad.objects.filter(sprint=self.pk)
        horas = 0
        for actividad in actividades:
            horas += actividad.duracion
        return horas

    def get_bdc_line(self):
        """
        metodo del modelo Sprint que retorna un JSON que representa la lista de coordenadas
        para el grafico de su correspondiente burn down chart y el total de horas trabajadas
        :return: lista de coordenadas para graficar el burn  down chart
        """
        if not self.fecha_inicio: return []
        coordenadas = []
        estimaciones = HistorialEstimaciones.objects.filter(sprint=self.pk)
        horas = 0
        for estimacion in estimaciones:
            horas += estimacion.duracion_estimada
        coordenadas.append({
                            'x': 0,
                            'y': horas
                            })
        inicio = self.fecha_inicio
        dias_habiles = self.get_dias_habiles()
        if self.fecha_fin:
            fin = self.fecha_fin
        else:
            fin = timezone.now().date()
        dia = inicio
        nro_dia = 1
        while dia <= fin:
            if dia.isoweekday() in dias_habiles:
                actividades = []
                actividades_query = Actividad.objects.filter(sprint=self.pk).order_by('fecha')
                for actividad in actividades_query:
                    if actividad.fecha.date() == dia:
                        actividades.append(actividad)
                horas_trabajadas = 0
                for actividad in actividades:
                    horas_trabajadas += actividad.duracion
                coordenadas.append({
                    'x': nro_dia,
                    'y': horas - horas_trabajadas
                })
                nro_dia += 1
                horas = horas - horas_trabajadas
            else:
                actividades = []
                actividades_query = Actividad.objects.filter(sprint=self.pk).order_by('fecha')
                for actividad in actividades_query:
                    if actividad.fecha.date() == dia:
                        actividades.append(actividad)
                horas_trabajadas = 0
                for actividad in actividades:
                    horas_trabajadas += actividad.duracion
                horas = horas - horas_trabajadas
                fin = fin + timedelta(days=1)
            dia = dia + timedelta(days=1)
        return coordenadas


class Horas(models.Model):
    """
    Modelo de Horas, el cual es una relacion entre un team member perteneciente al proyecto al
    que se relaciona el sprint en el que se están asignando las horas laborales
    """
    horas_laborales = models.IntegerField(blank=False, null=False)
    team_member = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE, null=True)
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE, null=True)

    def validate(self):
        """
        Metodo del modelo de Horas que lanza excepciones de tipo ValidationError en caso de
        que no se hayan completado dos los campos obligatorios en el sprint (horas laborales,
        team member, sprint) en caso contrario retorna verdadero
        """
        if not self.horas_laborales or self.horas_laborales == 0:
            raise ValidationError("Debe especificar horas laborales por dia laboral para el team member")
        if not self.sprint:
            raise ValidationError("Las horas laborales deben estar relacionadas a un sprint")
        if not self.team_member:
            raise ValidationError("Debe especificar un team member")
        return True

proyecto/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import *
from usuarios.models import Usuario


class CreateProjectForm(forms.ModelForm):
    """
    Formulario para la creacion de un nuevo Proyecto
    """
    class Meta:
        """
        Clase en la que se definen los datos necesarios y adicionales para inicializacion y
        visualizacion del formulario
        """
        model = Proyecto
        fields = ('nombre', 'cliente', 'descripcion')


class UpdateProjectForm(forms.ModelForm):
    """
    Formulario para la modificacion de un Proyecto
    """
    class Meta:
        """
        Clase en la que se definen los datos necesarios y adicionales para inicializacion y
        visualizacion del formulario
        """
        model = Proyecto
        fields = ('nombre', 'cliente', 'descripcion')


class TeamMemberForm(forms.ModelForm):
    """
    Formulario para la creacion del TeamMember
    """
    class Meta:
        """
        Clase en la que se definen los datos necesarios y adicionales para inicializacion y
        visualizacion del formulario
        """
        model = TeamMember
        exclude = ()
        fields = ('usuario', 'rol')


"""
Se define la base para el grupo de team members
"""
BaseTeamMemberFormSet = inlineformset_factory(Proyecto, TeamMember, form=TeamMemberForm, extra=1)

class TeamMemberFormSet(BaseTeamMemberFormSet):
    """
    Formulario para la validacion de los campos del TeamMember
    """
    def is_valid(self):
        """
        Retorna verdadero si existe al menos un formulario dentro del formset y todos los
        formularios en el formset tienen usuario y rol, en caso contrario retorna falso
        :return: True si el formset es valido; False si el formset no es valido
        """
        super(TeamMemberFormSet,self).is_valid()
        self.vacio = False
        self.sin_usuario = False
        self.sin_rol = False
        self.doble_usuario = False
        self.rol_doble = False
        if not self.forms:
            self.vacio = True
            return False
        all_delete = True
        usuarios = []
        roles = []
        for form in self.forms:
            #verificacion de roles unicos
            if form['rol'].value():
                rol = Rol.objects.get(pk=form['rol'].value())
                if rol.is_unique and form['rol'].value() in roles:
                    self.rol_doble = rol
                    return False
                if not form['rol'].value() in roles:
                    roles.append(form['rol'].value())
            # un usuario solo puede asignarse una vez
            if form['usuario'].value() and not form['usuario'].value() in usuarios:
                usuarios.append(form['usuario'].value())
            elif form['usuario'].value() and form['usuario'].value() in usuarios:
                if not form['DELETE'].value():
                    self.doble_usuario = Usuario.objects.get(pk=form['usuario'].value()).username
                    return False
            #existe al menos un form que no se elimina, por lo tanto el formset no esta vacio
            if not form['DELETE'].value():
                all_delete = False
            #todos los forms deben tener usuario
            if not form['usuario'].value() and not form['DELETE'].value():
                self.sin_usuario = True
                return False
            # todos los forms deben tener rol
            if not form['rol'].value() and not form['DELETE'].value():
                self.sin_rol = True
                return False
        #si todos los forms se van a eliminar
        if all_delete:
            self.vacio=True
            return False
        return True

templates/proyecto/ejecucion.html
{% if 'Ver Ejecucion de Proyecto' in permisos %}
{%include 'base.html'%}
<div class="container">
    <div class="head">
        <h1 align="center"> Ejecucion {{ object.nombre }} </h1>
        <hr>
        <h3 style="text-align: center">Proyecto: {{ project.nombre }}</h3>
    </div>
    <div class="body" style="">
        {% if 'Ver Definiciones de Proyecto' in permisos %}
        <a href="{% url 'update_options' object.pk %}" style="color: gray">
            <button type="button" class="btn btn-success" style="margin-left: 50em"style="background-color:blue; border-color:blue">
                Ir a Definición
            </button>
        </a>
        {% endif %}
        <div class="options" style="font-size: 1.5em; padding-top: 0em!important;;">
            {% if object.estado == "Activo" %}
                {% if 'Ver Sprints' in permisos %}
                <li>
                    <a href="{% url 'sprint_list' object.pk %}">Sprints</a>
                </li>
                {% endif %}
                {% if 'Ver User Stories' in permisos %}
                <li>
                    <a href="{% url 'user_story_list' object.pk %}">Administrar User Stories</a>
                </li>
                {% endif %}
                {% if 'Ver Product Backlog' in permisos %}
                <li>
                    <a href="{% url 'product_backlog' object.pk%}">Product Backlog</a>
                </li>
                {% endif %}
                {% if 'Asignar User Stories' in permisos %}
                <li>
                    {% if sprint_pendiente %}
                    <a href="{% url 'asignar_us' object.pk sprint_pendiente.pk %}">Planificar siguiente sprint</a>
                    {% else %}
                    <a href="#sinSprintPendiente" role="button" data-toggle="modal">Planificar siguiente sprint</a>
                    {% endif %}
                </li>
                {% endif %}
                {% if 'Ver Tablero' in permisos %}
                <li>
                    {% if sprint_actual %}
                    <a href="#tiposTablero" role="button" data-toggle="modal">Sprint actual</a>
                    {% else %}
                    <a href="#sinSprintActual" role="button" data-toggle="modal">Sprint actual</a>
                    {% endif %}
                </li>
                {% endif %}
                <li>
                <a target="_blank" href="{% url 'horas_trabajadas' object.pk%}">
                <i class="fas fa-file-pdf"></i> Horas Trabajadas</button>
                </a>
                </li>
                <br>
                <div class="container" align="right">
                    <form method="POST" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="terminar">
                        {% if 'Terminar Proyecto' in permisos %}
                        <button type="submit" class="btn btn-success">
                            <i class="far fa-stop-circle"></i> Terminar Proyecto
                        </button>
                        {% endif %}
                    </form>
                    <form method="POST" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="cancelar">
                        {% if 'Cancelar Proyecto' in permisos %}
                        <button type="submit" class="btn btn-success">
                            <i class="fas fa-ban"></i> Cancelar Proyecto
                        </button>
                        {% endif %}
                    </form>
                    <form method="POST" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="suspender">
                        {% if 'Suspender Proyecto' in permisos %}
                        <button type="submit" class="btn btn-success">
                            <i class="far fa-pause-circle"></i> Suspender Proyecto
                        </button>
                        {% endif %}
                    </form>
                </div>
            {% elif object.estado == "Pendiente" %}
                <h3>El proyecto aun no ha sido iniciado, favor inicie el proyecto.</h3>
                <br><br>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="iniciar" >
                    {% if 'Iniciar Proyecto' in permisos %}
                    <div class="container" align="right">
                        <button type="submit" class="btn btn-success">
                            <i class="fas fa-play-circle"></i> Iniciar Proyecto
                        </button>
                    </div>
                    {% endif %}
                </form>
            {% elif object.estado == "Suspendido" %}
                <li>
                    <a href="{% url 'product_backlog' object.pk%}">Product Backlog</a>
                </li>
                <br>
                <h4>El proyecto se encuentra suspendido, puede reiniciar el proyecto.</h4>
                {% if 'Ver Sprints' in permisos %}
                <li>
                    <a href="{% url 'sprint_list' object.pk %}">Sprints</a>
                </li>
                {% endif %}
                {% if 'Ver User Stories' in permisos %}
                <li>
                    <a href="{% url 'user_story_list' object.pk %}">Administrar User Stories</a>
                </li>
                {% endif %}
                {% if 'Ver Product Backlog' in permisos %}
                <li>
                    <a href="{% url 'product_backlog' object.pk%}">Product Backlog</a>
                </li>
                {% endif %}
                <li>
                <a target="_blank" href="{% url 'horas_trabajadas' object.pk%}">
                <i class="fas fa-file-pdf"></i> Horas Trabajadas</button>
                </a>
                </li>
                <br><br>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="reiniciar" >
                    {% if 'Reiniciar Proyecto' in permisos %}
                    <div class="container" align="right">
                        <button type="submit" class="btn btn-success">
                            <i class="fas fa-play-circle"></i> Reiniciar Proyecto
                        </button>
                    </div>
                    {% endif %}
                </form>
            {% elif object.estado == "Terminado" %}
                <h4>El proyecto se encuentra terminado.</h4>
                <br>
                {% if 'Ver Sprints' in permisos %}
                <li>
                    <a href="{% url 'sprint_list' object.pk %}">Sprints</a>
                </li>
                {% endif %}
                {% if 'Ver User Stories' in permisos %}
                <li>
                    <a href="{% url 'user_story_list' object.pk %}">Administrar User Stories</a>
                </li>
                {% endif %}
                {% if 'Ver Product Backlog' in permisos %}
                <li>
                    <a href="{% url 'product_backlog' object.pk%}">Product Backlog</a>
                </li>
                {% endif %}
                <li>
                <a target="_blank" href="{% url 'horas_trabajadas' object.pk%}">
                <i class="fas fa-file-pdf"></i> Horas Trabajadas</button>
                </a>
                </li>
            {% endif %}
        </div>
        <br><br><br>
        <hr>
        <br>
    </div>
</div>
<div id="sinSprintPendiente" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">No existe sprint pendiente</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>Debe crear un nuevo sprint para asignar User Stories</p>
            </div>
            {% if 'Crear Sprints' in permisos %}
            <div class="modal-footer">
                <a href="./sprints/create/"><button type="button" class="btn btn-success">
                    Crear Sprint</button></a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div id="sinSprintActual" class="modal fade modal-centrado">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">No existe sprint en proceso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            {% if sprint_pendiente %}
                <div class="modal-body">
                    <p>Existe un sprint pendiente: {{ sprint_pendiente.nombre }}</p>
                </div>
            {% else %}
            <div class="modal-body">
                <p>Se debe crear un nuevo sprint y asignar user stories</p>
            </div>
            {% endif %}
            {% if sprint_pendiente %}
            {% if 'Iniciar Sprints' in permisos %}
            <div class="modal-footer">
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">
                        <i class="far fa-play-circle"></i> Iniciar Sprint
                    </button>
                    <input type="hidden" name="iniciar_sprint" value="{{ sprint_pendiente.pk }}">
                </form>
            </div>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
<div id="tiposTablero" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content modal-flujos">
            <div class="modal-header" style="display: inline; text-align: center">
                <h4 style="display: inline;" class="modal-title">Sprint: {{ sprint_actual.nombre }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <h5 style="margin-left: 10em">Tableros:</h5>
                <div class="options-flujos" style="margin-left: 14em">
                    {% for flujo in flujos %}
                        {% if sprint_actual %}
                            <li>
                                <a href="{% url 'tablero' project.pk sprint_actual.pk flujo.pk %}">{{ flujo.nombre }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <form method="POST">
                    {% if sprint_actual %}
                        <a target="_blank" href="{% url 'prioridades' project.pk sprint_actual.pk%}">
                            <button type="button" class="btn btn-success">
                                <i class="fas fa-file-pdf"></i> Prioridades del Sprint</button>
                        </a>
                    {% endif %}
                    {% csrf_token %}
                    <input type="hidden" name="terminar_sprint" value="{{ sprint_actual.pk }}">
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-stop-circle"></i> Terminar Sprint
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- sin user stories para iniciar sprint -->
<div id="SinUserStories" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sprint sin user stories asignados</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                Debe asignar al menos un user story al sprint para iniciarlo
            </div>
        </div>
    </div>
</div>

<!--fin sin user stories para iniciar sprint -->
<!-- confirmar terminacion de sprint -->
<div id="ConfirmarTerminacionSprint" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sprint con user stories no terminados</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                Algunos user stories no han sido finalizados, está seguro que desea terminar el sprint?
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <form method="POST">
                    {% csrf_token %}
                    <input name="conf_terminar" type="hidden" value={{ sprint_actual.pk }}>
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-stop-circle"></i> Terminar Sprint
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!--fin confirmar terminacion de sprint -->
<script type="text/javascript">
    $(document).ready(function($) {
        {% if error %}
            {% if error == 'sinus' %}
                $("#SinUserStories").modal("show");
            {% endif %}
        {% endif %}
        {% if confirmar %}
            {% if confirmar == 'fin_sprint' %}
                $("#ConfirmarTerminacionSprint").modal("show");
            {% endif %}
        {% endif %}
    });
</script>

{% else %}
Permiso denegado (Ver Ejecucion de Proyecto)
{% endif %}

templates/proyecto/ver_proyecto.html
{% if 'Ver Proyectos' in permisos %}
{%include 'base.html'%}
<html>
<body>
<div class="container">
    <div class="head">
        <h1 align="center"> {{ title }} </h1>
        <hr>
    </div>
    <div class="register">
        <div class="container detalle" style="font-size: 25px">
            <li>Nombre: {{ object.nombre }}</li>
            <li>Fecha de Inicio:{{ object.fecha_inicio }}</li>
            <li>Fecha de Finalización:{{ object.fecha_fin }}</li>
            <li>Estado:{{ object.estado }}</li>
            <li>Descripcion:{{ object.descripcion }}</li>
            <li>F. De Inicio (Estimada): {{ object.fecha_ini_estimada }}</li>
            <li>F. De Finalización (Estimada): {{ object.fecha_fin_estimada }}</li>
        </div>
        <br>
        <div class="row">
            <a href="../../"><button type="button" class="btn submit-btn">Atras</button></a>
        </div>
        <hr>
    </div>
</div>
</body>
</html>
{% else %}
Permiso denegado
{% endif %}